version: '3.8'

services:
  postgres:
    image: postgres:16.1-alpine
    container_name: my_postgres
    environment:
      POSTGRES_DB: infotecs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asdf2345-
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_go_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: